server:
  port: 8090
  context-path: /
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mndc
    username: root
    password: root
#TODO : 추후 실제 서비스때 계정 및 패스워드 변경 필요
#TODO : 및 DB에 계정 생성 및 권한 부여 필요
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  profiles:
    include: oauth

custom:
  oauth2:
    kakao:
      client-id: c8c2eb353479ec0dcab44444610489f0
      client-secret: X0DNMUsl2eqYSTO3gU1EszKBQgskbap7
    naver:
      client-id: HUlPJQ3woHNacSAPETZg
      client-secret: UDPdHO0ViQ