coolsms:
  key: NCSFNGQWT6LR7VI3
  secret: WNSHSGKRJND0KRVVOIJXPUK2SHNS4ESA

server:
  port: 8090
  context-path: /
  encoding:
    charset: UTF-8
    enabled: true
    force: true

mybatis:
  mapper-locations: mapper/**/*.xml
  type-aliases-package: com.example.mndc

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mndc
    username: root
    password: root
#TODO : 추후 실제 서비스때 계정 및 패스워드 변경 필요
#TODO : 및 DB에 계정 생성 및 권한 부여 필요
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 386614050316-bk472t7nvctllv8jgr479ptde916qji2.apps.googleusercontent.com
            client-secret: iZpNWtYvdA827sUrtFPZowXS
            scope:
              - email
              - profile
          facebook:
            client-id: 166068028896823
            client-secret: b6ad01d4e4f70a561fb3b65f6de783e3
            scope:
              - email
              - public_profile
          naver:
            client-id: HUlPJQ3woHNacSAPETZg
            client-secret: UDPdHO0ViQ
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect_uri: http://localhost:8090/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response